"""Add bio to users

Revision ID: 1bf79c3dc6f2
Revises: e75f1c61d5d7
Create Date: 2025-05-25 17:01:08.297543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf79c3dc6f2'
down_revision = 'e75f1c61d5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
